cat: /etc/redhat-release: No such file or directory
test_0 (__main__.lab1a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for file creation: ./lab1a.py ... ok
test_a (__main__.lab1a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for errors running: ./lab1a.py ... ok
test_a1 (__main__.lab1a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test for correct shebang line: ./lab1a.py ... ok
test_b (__main__.lab1a)
[Lab 1] - [Investigation 3] - [Part 2] - printing - Test output for correct output "Hello world": ./lab1a.py ... ok
test_0 (__main__.lab1b)
[Lab 1] - [Investigation 4] - string objects & printing - Test for file creation: ./lab1b.py ... ok
test_a (__main__.lab1b)
[Lab 1] - [Investigation 4] - string objects & printing - Test for errors running: ./lab1b.py ... ok
test_a1 (__main__.lab1b)
[Lab 1] - [Investigation 4] - string objects & printing - Test for correct shebang line: ./lab1b.py ... ok
test_b (__main__.lab1b)
[Lab 1] - [Investigation 4] - string objects & printing - Test for correct output "How old are you Isaac?": ./lab1b.py ... ok
test_0 (__main__.lab1c)
[Lab 1] - [Investigation 4] - integer objects & printing - Test for file creation: ./lab1c.py ... ok
test_a (__main__.lab1c)
[Lab 1] - [Investigation 4] - integer objects & printing - Test for errors running: ./lab1c.py ... ok
test_a1 (__main__.lab1c)
[Lab 1] - [Investigation 4] - integer objects & printing - Test for correct shebang line: ./lab1c.py ... ok
test_b (__main__.lab1c)
[Lab 1] - [Investigation 4] - integer objects & printing - Test output for correct output "Isaac is 72 years old!": ./lab1c.py ... ok
test_0 (__main__.lab1d)
[Lab 1] - [Investigation 5] - math operators - Test for file creation: ./lab1d.py ... FAIL

======================================================================
FAIL: test_0 (__main__.lab1d)
[Lab 1] - [Investigation 5] - math operators - Test for file creation: ./lab1d.py
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/avi.koen/ops445/lab1/./CheckLab1.py", line 171, in test_0
    self.assertTrue( os.path.exists('./lab1d.py'), msg=error_output)
AssertionError: False is not true : your file cannot be found(HINT: make sure you AND your file are in the correct directory)

----------------------------------------------------------------------
Ran 13 tests in 0.285s

FAILED (failures=1)
OPS435 Lab Report - System Information for running ./CheckLab1.py
=================================================================
    User login name: avi.koen
    Linux system name: ca-on-a-akoen
    Linux system version: 
    Python executable: /Library/Developer/CommandLineTools/usr/bin/python3
    Python version: 396
    OS Platform: darwin
    Working Directory: /Users/avi.koen/ops445/lab1
    Start at: Wed May 15 14:36:36 2024
=================================================================
